### ISSUE TITLE
What about passing `-t` to `delete-certificate` to remove trust settings

### ISSUE THREAD

**Issue by ghost** [sammcj/delete-unknown-root-ca#3]
per the [man](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/security.1.html) page (sorry I can’t link more specifically than this)

**Comment by sammcj** [comment]
Reading the man page for -t - That certainly seems like a good idea.
Will update shortly, thank you for the suggestion.

**Comment by ghost** [comment]
I can submit a PR, I didn't want to while #2 was open.

**Comment by sammcj** [comment]
Thanks - I'm in AU Timezone so was fast asleep :)
